import React, { useEffect, useState } from 'react'
import Mailjs from '@cemalgnlts/mailjs'
import { useNavigate } from 'react-router-dom'
import { Loader } from 'rsuite'
import { loginWithToken } from '../../utils/mailLoginWithToken'
import MailHeader from './MailHeader'
import MailMessages from './MailMessages'

import MailModal from './MailModal'

type Credentials = {
  username: string
  password?: string
  autoGenerated: boolean
}

type IStorage = {
  quota: number
  used: number
}

const TempMail = () => {
  const mailjs = new Mailjs()
  const history = useNavigate()

  const [loading, setLoading] = useState(true)
  const [credentials, setCredentials] = useState<Credentials>(null)
  const [showLoginModal, setShowLoginModal] = useState(false)
  const [messages, setMessages] = useState(null)
  const [storage, setStorage] = useState<IStorage>(null)

  useEffect(() => {
    setLoading(true)
    const isLoggedIn = window.localStorage.getItem('isLoggedIn')
    const token = window.localStorage.getItem('token')
    if (isLoggedIn == 'true' && token) {
      setShowLoginModal(false)
      Promise.all([loginWithToken(token, mailjs, setStorage)])
        .then(() => {
          mailjs.getMessages().then(res => setMessages(res.data))
          setCredentials({ username: mailjs.address, autoGenerated: false })
        })
        .then(() => setLoading(false))
    } else {
      setLoading(false)
      setShowLoginModal(true)
    }
  }, [])

  useEffect(() => {
    credentials &&
      credentials.password &&
      mailjs.login(credentials.username, credentials.password).then((res: any) => {
        window.localStorage.setItem('token', res.data.token)
        window.localStorage.setItem('isLoggedIn', 'true')
        Promise.all([
          mailjs.me().then(res => setStorage({ quota: res.data.quota, used: res.data.used })),
          mailjs.getMessages().then(res => setMessages(res.data))
        ]).then(() => setLoading(false))
      })
  }, [credentials])

  if (loading) {
    return <Loader size={'lg'} backdrop content='loading...' vertical />
  }

  return (
    <div className='page-container'>
      {!loading && credentials && storage && messages && (
        <>
          <h3>Temp Mail 📨</h3>
          <div className='tempMail__container'>
            <MailHeader
              credentials={credentials}
              setShowLoginModal={setShowLoginModal}
              setCredentials={setCredentials}
              setMessages={setMessages}
              storage={storage}
            />
            <MailMessages messages={messages} />
          </div>
        </>
      )}
      <MailModal
        mailjs={mailjs}
        showLoginModal={showLoginModal}
        setShowLoginModal={setShowLoginModal}
        history={history}
        setCredentials={setCredentials}
      />
    </div>
  )
}

export default TempMail
